-- Drop table if it already exists
drop Table qshonitmp.test;
-- Create table and insert a few records
Create Table qshonitmp.test (name Char(10) Ccsid 37 Not Null Default ' ');
Insert Into qshonitmp.test
  Values
    ('Test1');
Insert Into qshonitmp.test
  Values
    ('Test2');
-- Add new id column and update id field with correct values
Alter Table qshonitmp.test
  Add Column id Bigint Generated By Default As Identity (
  Start With 1 Increment By 1 Minvalue 1 Maxvalue 9223372036854775807 No Cycle
  No Order Cache 20
);
