-- This SQL query lists only objects that don't match their source.
-- Change the library name or add a library placeholder of @@LIBRARY
--  if using with the QSHONI/QSHQRYSRC command 
WITH OBJECT_SOURCE AS
(
    SELECT
        O.OBJLIB,
        O.OBJNAME,
        O.OBJTYPE,
        O.OBJATTRIBUTE,
        O.OBJTEXT,
        O.OBJCREATED,
        O.SOURCE_LIBRARY,
        O.SOURCE_FILE,
        O.SOURCE_MEMBER,
        O.SOURCE_TIMESTAMP
    FROM TABLE
    (
        QSYS2.OBJECT_STATISTICS(
            'QSHONI',
            '*ALL'
        )
    ) AS O
    WHERE O.SOURCE_LIBRARY IS NOT NULL
      AND O.SOURCE_FILE    IS NOT NULL
      AND O.SOURCE_MEMBER  IS NOT NULL
)
SELECT
    O.OBJLIB                        AS OBJECT_LIBRARY,
    O.OBJNAME                       AS OBJECT_NAME,
    O.OBJTYPE                       AS OBJECT_TYPE,
    O.OBJATTRIBUTE                  AS OBJECT_ATTRIBUTE,
    O.OBJTEXT                       AS OBJECT_TEXT,
    O.OBJCREATED                    AS OBJECT_CREATED,

    O.SOURCE_LIBRARY                AS SOURCE_LIBRARY,
    O.SOURCE_FILE                   AS SOURCE_FILE,
    O.SOURCE_MEMBER                 AS SOURCE_MEMBER,

    O.SOURCE_TIMESTAMP              AS OBJECT_SOURCE_TIMESTAMP,
    S.LAST_SOURCE_UPDATE_TIMESTAMP  AS CURRENT_SOURCE_TIMESTAMP,
    S.SOURCE_TYPE                   AS CURRENT_SOURCE_TYPE,

    CASE
        WHEN S.SYSTEM_TABLE_MEMBER IS NULL
            THEN 'SOURCE MEMBER NOT FOUND'

        WHEN O.SOURCE_TIMESTAMP IS NULL
            THEN 'OBJECT SOURCE TIMESTAMP MISSING'

        WHEN S.LAST_SOURCE_UPDATE_TIMESTAMP IS NULL
            THEN 'CURRENT SOURCE TIMESTAMP MISSING'

        WHEN S.LAST_SOURCE_UPDATE_TIMESTAMP
             > O.SOURCE_TIMESTAMP
            THEN 'SOURCE CHANGED AFTER COMPILE'

        WHEN S.LAST_SOURCE_UPDATE_TIMESTAMP
             < O.SOURCE_TIMESTAMP
            THEN 'SOURCE OLDER THAN OBJECT SOURCE'

        ELSE 'MATCH'
    END AS SOURCE_STATUS

FROM OBJECT_SOURCE AS O

LEFT JOIN QSYS2.SYSPARTITIONSTAT AS S
  ON S.SYSTEM_TABLE_SCHEMA = O.SOURCE_LIBRARY
 AND S.SYSTEM_TABLE_NAME   = O.SOURCE_FILE
 AND S.SYSTEM_TABLE_MEMBER = O.SOURCE_MEMBER

WHERE S.SYSTEM_TABLE_MEMBER IS NULL
   OR O.SOURCE_TIMESTAMP IS NULL
   OR S.LAST_SOURCE_UPDATE_TIMESTAMP IS NULL
   OR S.LAST_SOURCE_UPDATE_TIMESTAMP
        <> O.SOURCE_TIMESTAMP

ORDER BY
    O.OBJLIB,
    O.OBJTYPE,
    O.OBJNAME;
